---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Shared stack for the Small Apps Domain'

Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
  RootDomainZoneID:
    Description: The zone ID of the root domain
    Type: String
  RootDomain:
    Description: The root domain
    Type: String
  SubDomain:
    Description: The sub domain to create for the core resources.
    Type: String

Mappings:
<%= partial('mappings/region-map.yaml.erb', {}, indent: 2) %>


Resources:
<%= partial('route53/hosted-zone.yaml.erb',
            id: 'SharedResourcesZone',
            comment: "!Join [' ' , ['Root Domain for:', !Ref ProjectName]]",
            name: "!Join [., [!Ref SubDomain, !Ref RootDomain]]",
            tags: [{'key' => 'Example', 'value' => 'Tag'}]) %>
<%= partial('codecommit/repository.yaml.erb',
            id: 'SharedResourcesRepo',
            name: '!Ref ProjectName',
            description: "!Join [' ' , ['Git repository for:', !Ref ProjectName]]") %>

Outputs:
  GitRepo:
    Description: The name of the Git repository
    Value: !GetAtt [SharedResourcesRepo, Name]
  GitRepoCloneUrlHttp:
    Description: The URL to clone the Git repository via HTTP
    Value: !GetAtt [SharedResourcesRepo, CloneUrlHttp]
  GitRepoCloneUrlSsh:
    Description: The URL to clone the Git repository via SSH
    Value: !GetAtt [SharedResourcesRepo, CloneUrlSsh]
  ZoneID:
    Description: The zone id for the newly created zone
    Value:
      Ref: 'SharedResourcesZone'
  DomainName:
    Description: The newly created domain name
    Value: !Join [., [!Ref SubDomain, !Ref RootDomain]]
