---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Production stack for the Small Apps Domain'

Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
  CloudFrontId:
    Description: The ID of the CloudFront distribution
    Type: String

Mappings:
<%= partial('mappings/region-map.yaml.erb', {}, indent: 2) %>

Resources:

  # ---------------------------------------------------------------------------
  # IAM Security Role for the <%= @environment %> pipeline
  # ---------------------------------------------------------------------------

  <%
    appBucketName = @appBucketName + "prod"
    testAppBucketName = @stagingBucket + "test"
    codebuildsArry = [
      "ApplicationUploadBuild"
    ]
    s3Arry = {
      'names' => [appBucketName, testAppBucketName]
    }
    pipelineRoleId = 'PipelineRole'
    pipelineId = 'ProductionPipeline'
    buildId = 'ApplicationUploadBuild'
  %>

<%= partial('iam/pipeline-assumed-role.yaml.erb',
            id: pipelineRoleId,
            codebuilds: codebuildsArry,
            s3s: s3Arry) %>

  # ---------------------------------------------------------------------------
  # CodeBuild configuration
  # ---------------------------------------------------------------------------

<%= partial('codebuild/s3-upload-from-s3.yaml.erb',
            id: buildId,
            buildSpec: 'codebuild/buildspecs/copy-s3-to-s3.yaml.erb',
            environmentVars: 'codebuild/environmentVars/copy-s3-to-s3.yaml.erb',
            cloudfront: true,
            cloudfrontLogicalId: '!Ref CloudFrontId',
            role: pipelineRoleId,
            source: testAppBucketName,
            dest: appBucketName) %>

  # ---------------------------------------------------------------------------
  # Access Policies
  # ---------------------------------------------------------------------------

<%= partial('iam/policies/codebuild.yaml.erb',
            id: 'CodeBuildAccessPolicy',
            codebuilds: codebuildsArry) %>

  # --------------------------------------------------------------------------
  # Outputs
  # --------------------------------------------------------------------------

Outputs:
  CodeBuildPolicy:
    Description: The policy which allows access to CodeBuild
    Value:
      Ref: 'CodeBuildAccessPolicy'
