---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Production stack for the Small Apps Domain'

Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
  IndexDocument:
    Description: The index document for static S3 websites
    Type: String
    Default: index.html

Mappings:
<%= partial('mappings/region-map.yaml.erb', {}, indent: 2) %>

Resources:

  # ---------------------------------------------------------------------------
  # IAM Security Role for the pipeline to assume
  # ---------------------------------------------------------------------------

  <%
    appBucket = @appBucketName + "test"
    stagingBucket =  stagingBucket = @stagingBucket + "test"
    codebuildsArry = [
        "ApplicationUploadBuild"
    ]
    s3Arry = {
        'names' => [@appBucketName + "test"],
        'arns' => ['TestPipelineStagingBucket']
    }
    codecommitNames = []
    @projects.each do |project|
      codecommitNames.push(project['name'])
    end
    pipelineRoleId = 'PipelineRole'
    pipelineId = 'TestPipeline'
    buildId = 'ApplicationUploadBuild'
    stagingBucketId = pipelineId + 'StagingBucket'
  %>

<%= partial('iam/pipeline-assumed-role.yaml.erb',
            id: pipelineRoleId,
            codebuilds: codebuildsArry,
            s3s: s3Arry,
            codecommitNames: codecommitNames) %>

  # ---------------------------------------------------------------------------
  # CodeBuild configuration
  # ---------------------------------------------------------------------------

<%= partial('codebuild/s3-upload.yaml.erb',
            id: buildId,
            buildSpec: 'codebuild/buildspecs/static-website.yaml.erb',
            environmentVars: 'codebuild/environmentVars/static-website.yaml.erb',
            stagingBucket: stagingBucketId,
            role: pipelineRoleId,
            appBucket: appBucket,
            cloudfront: false) %>

  # ---------------------------------------------------------------------------
  # Pipeline definition
  # ---------------------------------------------------------------------------

<%= partial('s3/versioned-bucket.yaml.erb',
            id: stagingBucketId,
            name: stagingBucket) %>

<%= partial('codepipeline/s3-static-website-pipeline.yaml.erb',
            id: pipelineId,
            role: pipelineRoleId,
            buildName: buildId,
            testing: true,
            branch: 'master',
            autotrigger: false,
            stagingBucket: stagingBucketId) %>

  # ---------------------------------------------------------------------------
  # Access Policies
  # ---------------------------------------------------------------------------

<%= partial('iam/policies/codebuild.yaml.erb',
            id: 'CodeBuildAccessPolicy',
            codebuilds: codebuildsArry) %>

<%= partial('iam/policies/codepipeline.yaml.erb',
            id: 'CodePipelineAccessPolicy',
            pipelines: [pipelineId]) %>

  # --------------------------------------------------------------------------
  # Outputs
  # --------------------------------------------------------------------------

Outputs:
  CodeBuildPolicy:
    Description: The policy which allows access to CodeBuild
    Value:
      Ref: 'CodeBuildAccessPolicy'
  CodePipelinePolicy:
    Description: The policy which allows access to CodePipeline
    Value:
      Ref: 'CodePipelineAccessPolicy'
