AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BuildProjectName:
    Description: Name of the build project
    Type: String
  CodeCommitProject:
    Description: The name of the AWS Code Commit project to build
    Type: String
  DevBucketName:
    Description: S3 bucket for dev app
    Type: String
  PipelineName:
    Description: Name of the pipeline
    Type: String
  PipelinePolicyName:
    Description: Name of the security policy
    Type: String
  PipelineRoleName:
    Description: Name of the security Role
    Type: String
  ProdBucketName:
    Description: S3 bucket for prod app
    Type: String
  RootDomainZoneID:
    Description: The zone ID of the root domain
    Type: String
  S3Bucket:
    Description: The URI for the S3 bucket containing the templates
    Type: String
  StagingBucketName:
    Description: The name of the staging s3 bucket for development
    Type: String
Resources:
  DevAppBucket:
    Properties:
      Parameters:
        NewSubDomain:
          Ref: DevBucketName
        RootDomainZoneID:
          Ref: RootDomainZoneID
      TemplateURL:
        Fn::Join:
        - /
        - - Ref: S3Bucket
          - templates
          - s3
          - www-bucket.template
      TimeoutInMinutes: '60'
    Type: AWS::CloudFormation::Stack
  DevBuild:
    DependsOn:
    - DevSecurityRole
    Properties:
      Parameters:
        Environment: dev
        Name:
          Ref: BuildProjectName
        RoleName:
          Fn::Join:
          - '-'
          - - Ref: PipelineRoleName
            - dev
        S3Bucket:
          Ref: DevBucketName
      TemplateURL:
        Fn::Join:
        - /
        - - Ref: S3Bucket
          - templates
          - codebuild
          - s3-upload.template
      TimeoutInMinutes: '60'
    Type: AWS::CloudFormation::Stack
  DevSecurityRole:
    Properties:
      Parameters:
        BuildProjectName:
          Fn::Join:
          - '-'
          - - Ref: BuildProjectName
            - dev
        CodeCommitProject:
          Ref: CodeCommitProject
        PipelineName:
          Fn::Join:
          - '-'
          - - Ref: PipelineName
            - dev
        PolicyName:
          Fn::Join:
          - '-'
          - - Ref: PipelinePolicyName
            - dev
        RoleName:
          Fn::Join:
          - '-'
          - - Ref: PipelineRoleName
            - dev
        S3AppBucket:
          Ref: DevBucketName
        S3StagingBucket:
          Ref: StagingBucketName
      TemplateURL:
        Fn::Join:
        - /
        - - Ref: S3Bucket
          - templates
          - iam
          - pipeline-iam.template
      TimeoutInMinutes: '60'
    Type: AWS::CloudFormation::Stack
  DevelopmentPipeline:
    DependsOn:
    - DevSecurityRole
    - DevBuild
    - DevAppBucket
    - StagingBucket
    Properties:
      ArtifactStore:
        Location:
          Ref: StagingBucketName
        Type: S3
      Name:
        Fn::Join:
        - '-'
        - - Ref: PipelineName
          - dev
      RoleArn:
        Fn::Join:
        - /
        - - arn:aws:iam::977855701381:role
          - Fn::Join:
            - '-'
            - - Ref: PipelineRoleName
              - dev
      Stages:
      - Actions:
        - ActionTypeId:
            Category: Source
            Owner: AWS
            Provider: CodeCommit
            Version: '1'
          Configuration:
            BranchName: develop
            RepositoryName:
              Ref: CodeCommitProject
          Name: ApplicationSource
          OutputArtifacts:
          - Name: app-source
          RunOrder: 1
        Name: Source
      - Actions:
        - ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          Configuration:
            ProjectName:
              Fn::Join:
              - '-'
              - - Ref: BuildProjectName
                - dev
          InputArtifacts:
          - Name: app-source
          Name: Deployment
          RunOrder: 1
        Name: Build
    Type: AWS::CodePipeline::Pipeline
  ProdAppBucket:
    Properties:
      Parameters:
        NewSubDomain:
          Ref: ProdBucketName
        RootDomainZoneID:
          Ref: RootDomainZoneID
      TemplateURL:
        Fn::Join:
        - /
        - - Ref: S3Bucket
          - templates
          - s3
          - www-bucket.template
      TimeoutInMinutes: '60'
    Type: AWS::CloudFormation::Stack
  ProdBuild:
    DependsOn:
    - ProdSecurityRole
    Properties:
      Parameters:
        Environment: prod
        Name:
          Ref: BuildProjectName
        RoleName:
          Fn::Join:
          - '-'
          - - Ref: PipelineRoleName
            - prod
        S3Bucket:
          Ref: ProdBucketName
      TemplateURL:
        Fn::Join:
        - /
        - - Ref: S3Bucket
          - templates
          - codebuild
          - s3-upload.template
      TimeoutInMinutes: '60'
    Type: AWS::CloudFormation::Stack
  ProdSecurityRole:
    Properties:
      Parameters:
        BuildProjectName:
          Fn::Join:
          - '-'
          - - Ref: BuildProjectName
            - prod
        CodeCommitProject:
          Ref: CodeCommitProject
        PipelineName:
          Fn::Join:
          - '-'
          - - Ref: PipelineName
            - prod
        PolicyName:
          Fn::Join:
          - '-'
          - - Ref: PipelinePolicyName
            - prod
        RoleName:
          Fn::Join:
          - '-'
          - - Ref: PipelineRoleName
            - prod
        S3AppBucket:
          Ref: ProdBucketName
        S3StagingBucket:
          Ref: StagingBucketName
      TemplateURL:
        Fn::Join:
        - /
        - - Ref: S3Bucket
          - templates
          - iam
          - pipeline-iam.template
      TimeoutInMinutes: '60'
    Type: AWS::CloudFormation::Stack
  ProductionPipeline:
    DependsOn:
    - ProdSecurityRole
    - ProdBuild
    - ProdAppBucket
    - StagingBucket
    Properties:
      ArtifactStore:
        Location:
          Ref: StagingBucketName
        Type: S3
      Name:
        Fn::Join:
        - '-'
        - - Ref: PipelineName
          - prod
      RoleArn:
        Fn::Join:
        - /
        - - arn:aws:iam::977855701381:role
          - Fn::Join:
            - '-'
            - - Ref: PipelineRoleName
              - prod
      Stages:
      - Actions:
        - ActionTypeId:
            Category: Source
            Owner: AWS
            Provider: CodeCommit
            Version: '1'
          Configuration:
            BranchName: master
            PollForSourceChanges: 'false'
            RepositoryName:
              Ref: CodeCommitProject
          Name: ApplicationSource
          OutputArtifacts:
          - Name: app-source
          RunOrder: 1
        Name: Source
      - Actions:
        - ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          Configuration:
            ProjectName:
              Fn::Join:
              - '-'
              - - Ref: BuildProjectName
                - prod
          InputArtifacts:
          - Name: app-source
          Name: Deployment
          RunOrder: 1
        Name: Build
    Type: AWS::CodePipeline::Pipeline
  StagingBucket:
    Properties:
      Parameters:
        Name:
          Ref: StagingBucketName
      TemplateURL:
        Fn::Join:
        - /
        - - Ref: S3Bucket
          - templates
          - s3
          - default-bucket.template
      TimeoutInMinutes: '60'
    Type: AWS::CloudFormation::Stack
