---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Production stack for the Small Apps Domain'

Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
    Default: <%= @projectName %>
  RootDomainZoneID:
    Description: The zone ID of the root domain
    Type: String
    Default: ''
  RootDomain:
    Description: The root domain
    Type: String
  IndexDocument:
    Description: The index document for static S3 websites
    Type: String
    Default: index.html
  CloudFrontOriginAccessIdentityResource:
    Description: The ARN for the resource which creates cloudfront origin access identities
    Type: String

Mappings:
<%= partial('mappings/region-map.yaml.erb', {}, indent: 2) %>

Resources:

  # ---------------------------------------------------------------------------
  # S3 Static Website Bucket
  # ---------------------------------------------------------------------------

  <%
    appBucketId = 'AppBucket'
    appBucketName = @appBucketName + "prod"
  %>

  OriginAccessIdentity:
    Type: 'AWS::CloudFormation::CustomResource'
    Properties:
      ServiceToken: !Ref CloudFrontOriginAccessIdentityResource
      Reference: !Ref ProjectName
      Comment: !Sub 'CloudFront origin access identity for: ${ProjectName}'

<%= partial('s3/versioned-bucket.yaml.erb',
            id: appBucketId,
            name: appBucketName) %>
<%= partial('s3/policy/cloudfront-origin-access-identity.yaml.erb',
            id: appBucketId,
            canonicalUser: '!GetAtt [OriginAccessIdentity, S3CanonicalUserId]',
            bucketName: appBucketName) %>

<% if @enableDNS %>
  # ---------------------------------------------------------------------------
  # Route 53 Configuration
  # ---------------------------------------------------------------------------

<%= partial('route53/hosted-zone.yaml.erb',
           id: 'ProductionZone',
           name: "!Join ['.', [!Ref ProjectName, !Ref RootDomain]]",
           comment: "!Join [' ', ['Hosted zone for:', !Ref ProjectName]]") %>

  # ---------------------------------------------------------------------------
  # WAF Configuration
  # ---------------------------------------------------------------------------

<%= partial('waf/predicates/IPSet.yaml.erb',
            id: 'ProductionIPSet',
            ipSet: @ip_white_list) %>

<%= partial('waf/rule.yaml.erb',
            id: 'ProductionIPSetRule',
            name: "ipsrule",
            predicates: [{'id' => 'ProductionIPSet', 'type' => 'IPMatch'}]) %>

<%= partial('waf/web-acl.yaml.erb',
            id: 'ProductionWebAcl',
            name: "!Join ['', [!Ref ProjectName, Access]]",
            rules: ['ProductionIPSetRule']) %>

  # ---------------------------------------------------------------------------
  # CloudFront Configuration
  # ---------------------------------------------------------------------------

<%= partial('cloudfront/cloudfront.yaml.erb',
           id: 'Production',
           dependsOn: ['ProductionZone', 'ProductionWebAcl'],
           webAcl: 'ProductionWebAcl',
           bucketName: "!Sub '#{appBucketName}'",
           hostedZone: "!Join ['.', [!Ref 'ProjectName', !Ref 'RootDomain', '']]",
           originAccessIdentity: '!GetAtt [OriginAccessIdentity, Id]') %>


<% end %>

  # --------------------------------------------------------------------------
  # Outputs
  # --------------------------------------------------------------------------

Outputs:
  WebsiteUrl:
    Description: The URL to connect to the website via CloudFront
    Value: !Join ['.', ['http://www', !Ref ProjectName, !Ref RootDomain]]
  AppBucketArn:
    Description: The ARN of the S3 bucket which hosts the app
    Value: !GetAtt [<%= appBucketId %>, Arn]
<% if @enableDNS %>
  CloudFrontId:
    Description: The ID of the CloudFront distribution
    Value:
      Ref: ProductionCloudfront
<% end %>
