service: origin-access-identity

provider:
  name: aws
  runtime: python3.6
  region: eu-west-2
  variableSyntax: '\${{([\s\S]+?)}}'
  deploymentBucket:
    name: cbscl-s3-lambda-538162597997-eu-west-2
    serverSideEncryption: AES256
  iamRoleStatements:
    - Action:
      - "cloudfront:CreateCloudFrontOriginAccessIdentity"
      - "cloudfront:ListCloudFrontOriginAccessIdentities"
      - "cloudfront:GetCloudFrontOriginAccessIdentityConfig"
      - "cloudfront:UpdateCloudFrontOriginAccessIdentity"
      - "cloudfront:DeleteCloudFrontOriginAccessIdentity"
      Resource:
        - '*'
      Effect: 'Allow'
    - Action:
      - "s3:PutObject"
      - "s3:PutObjectAcl"
      - "s3:GetObject"
      - "s3:GetObjectVersion"
      - "s3:*"
      Resource:
      - Fn::Sub: 'arn:aws:s3:::cbscl-s3-lambda-538162597997-eu-west-2/*'
      Effect: "Allow"
    - Action:
      - "s3:ListBucket"
      Resource:
      - Fn::Sub: 'arn:aws:s3:::cbscl-s3-lambda-538162597997-eu-west-2'
      Effect: "Allow"
    - Action:
      - "logs:CreateLogGroup"
      - "logs:CreateLogStream"
      - "logs:PutLogEvents"
      Resource:
      - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/create-origin-access-identity:log-stream:*
      Effect: "Allow"
package:
  exclude:
    - .gitignore
    - README.md
functions:
  createoriginaccessidentity:
    handler: lambda_function.lambda_handler
