---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Project root stack for the Small Apps Domain'

Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
    Default: <%= @projectName %>

Mappings:
<%= partial('mappings/environment-configuration.yaml.erb') %>

Resources:
<%= partial('cloudformation/stack.yaml.erb',
            id: "DevelopmentStack",
            url: template_s3_path('stacks/pipeline/development-sad-pipeline'),
            params: [{'key' => 'ProjectName', 'value' => '!Ref ProjectName'}],
            tags: @devTags) %>
<%= partial('cloudformation/stack.yaml.erb',
            id: "TestStack",
            url: template_s3_path("stacks/pipeline/test-sad-pipeline"),
            params: [{'key' => 'ProjectName', 'value' => '!Ref ProjectName'}],
            tags: @testTags) %>
<%# partial('cloudformation/stack.yaml.erb',
  #          id: "ProductionStack",
  #          url: template_s3_path("stacks/pipeline/production-sad-pipeline"),
  #          params: [{'key' => 'ProjectName', 'value' => '!Ref ProjectName'}],
  #          tags: @prodTags) %>
