service: lightsail-auto-snapshots

provider:
  name: aws
  runtime: python3.6
  region: eu-west-2
  variableSyntax: '\${{([\s\S]+?)}}'
  deploymentBucket:
    name: cbscl-s3-lambda-538162597997-eu-west-2
    serverSideEncryption: AES256
  iamRoleStatements:
    - Action:
        - "lightsail:GetInstances"
        - "lightsail:GetInstanceSnapshots"
        - "lightsail:CreateInstanceSnapshot"
        - "lightsail:DeleteInstanceSnapshot"
      Resource:
        - "*"
      Effect: "Allow"
    - Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource:
        - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lightsail-auto-snapshots:log-stream:*
      Effect: "Allow"
package:
  exclude:
    - .gitignore
functions:
  createsnapshots:
    handler: lambda_function.lambda_handler
    events:
      - schedule:
          rate: rate(1 day)
          enabled: true
