---
AWSTemplateFormatVersion: 2010-09-09
Description: 'Root stack for the Small Apps Domain'

Parameters:
  RootDomainZoneID:
    Description: The zone ID of the root domain
    Type: String
    Default: ''
  RootDomain:
    Description: The root domain
    Type: String

Mappings:
<%= partial('mappings/region-map.yaml.erb', {}, indent: 2) %>
<%= partial('mappings/environment-configuration.yaml.erb') %>

Resources:
  <% @stacks.each do |stack| %>
  <% key = stack['key'] %>
<%= partial('cloudformation/stack.yaml.erb',
            id: stack['id'],
            url: template_s3_path(key),
            params: stack['params'],
            tags: @tags || @core_tags,
            devTags: stack['devTags'],
            testTags: stack['testTags'],
            prodTags: stack['prodTags']) %>

  <% end %>
